workflows:
  ios-workflow:
    name: iOS App Build
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_connect_credentials
      vars:
        BUNDLE_ID: "com.solarcityuk.solarCityV2"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set iOS deployment target
        script: | 
          #!/bin/sh
          set -e
          set -x
          PODFILE_PATH=$(find ios -name Podfile)
          if [ -f "$PODFILE_PATH" ]; then
            sed -i.bak "2i\\
            platform :ios, '13.0'
            " "$PODFILE_PATH"
            echo "Podfile successfully modified."
          else
            echo "Podfile not found, attempting to set via .xcconfig"
            echo "IPHONEOS_DEPLOYMENT_TARGET = 13.0" >> ios/Flutter/Debug.xcconfig
            echo "IPHONEOS_DEPLOYMENT_TARGET = 13.0" >> ios/Flutter/Release.xcconfig
          fi
      - name: Flutter packages get
        script: flutter packages pub get
      - name: Set Bundle ID in Xcode project
        script: /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "ios/Runner/Info.plist"
      - name: Set up code signing for Development
        script: xcode-project use-profiles --profile-type=DEVELOPMENT
      - name: Build iOS App
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa