workflows:
  ios-workflow:
    name: iOS App Build
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_connect_credentials
      vars:
        BUNDLE_ID: "com.solarcityuk.solarCityV2" # Make sure this is your exact Bundle ID
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set iOS deployment target
        script: | 
          #!/bin/sh
          set -e
          set -x
          PODFILE_PATH=$(find ios -name Podfile)
          if [ -f "$PODFILE_PATH" ]; then
            sed -i.bak "2i\\
            platform :ios, '13.0'
            " "$PODFILE_PATH"
          else
            echo "IPHONEOS_DEPLOYMENT_TARGET = 13.0" >> ios/Flutter/Debug.xcconfig
            echo "IPHONEOS_DEPLOYMENT_TARGET = 13.0" >> ios/Flutter/Release.xcconfig
          fi
      - name: Flutter packages get
        script: flutter packages pub get
      - name: Set Bundle ID in Xcode project
        script: /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $BUNDLE_ID" "ios/Runner/Info.plist"
      - name: Build iOS App
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID