workflows:
  ios-workflow:
    name: iOS App Build
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_connect_credentials
      vars:
        BUNDLE_ID: "com.solarcityuk.solarCityMobile"
        flutter: stable
      xcode: latest
      cocoapods: default
    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.solarcityuk.solarCityMobile
    scripts:
      - name: Flutter packages get
        script: flutter packages pub get
      - name: Build iOS App
        script: | 
          set -ex
          flutter build ipa --release --export-method app-store
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID